dist: xenial
language: php
compiler:
    - gcc
addons:
    apt:
        packages:
            - valgrind
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - nightly
matrix:
    allow_failures:
        - php: nightly
env:
    - LIBRDKAFKA_VERSION=0.11.x
    - LIBRDKAFKA_VERSION=v1.0.1
    - LIBRDKAFKA_VERSION=v1.1.0
    - LIBRDKAFKA_VERSION=master
script: ./.travis/build.sh
