version: "3"
services:

  zk:
    build: ../kafka/zookeeper
    container_name: zk
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk:2888:3888
    networks:
      - backend

  kafka:
    build: ./kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zk
    networks:
      - backend

  kafka-manager:
    build: ./kafka-manager
    ports:
      - "9111:9000"
    environment:
      ZK_HOSTS: zk:2181
      KAFKA_BROKERS: kafka:9092
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
